version: "2"
linters:
  default: none
  enable:
    - asasalint
    - bodyclose
    - depguard
    - errorlint
    - gocheckcompilerdirectives
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - wastedassign
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: io/ioutil package has been deprecated.
    dupl:
      threshold: 100
    errorlint:
      errorf: false
      errorf-multi: false
      asserts: false
      comparison: true
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - ifElseChain
        - wrapperFunc
        - hugeParam
        - rangeValCopy
        - appendCombine
        - commentedOutCode
        - sloppyReassign
        - filepathJoin
        - evalOrder
        - equalFold
        - returnAfterHttpError
        - preferStringWriter
        - sprintfQuotedString
        - preferFprint
      enabled-tags:
        - diagnostic
        - performance
    govet:
      enable:
        - nilness
    nolintlint:
      require-explanation: false
      require-specific: false
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: time-naming
        - name: errorf
        - name: unreachable-code
        - name: redefines-builtin-id
    staticcheck:
      checks:
        - all
        - -SA1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/spacelift-io/spacectl)
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/spacelift-io/backend
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
