builds:
  - env:
      - CGO_ENABLED=0
      - GOPRIVATE="github.com/spacelift-io"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags: [-trimpath, -v]
    goos: [windows, linux, darwin]
    goarch: [amd64, arm64]
    binary: "{{ .ProjectName }}"

archives:
  # Our GitHub Action relies on this format and file path, so please don't change it:
  # https://github.com/spacelift-io/setup-spacectl
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
  - use: buildx
    goarch: amd64
    build_flag_templates:
     - "--platform=linux/amd64"
     - "--label=org.opencontainers.image.title={{ .ProjectName }}"
     - "--label=org.opencontainers.image.vendor=Spacelift"
     - "--label=org.opencontainers.image.description=Spacelift CLI version {{ .Version }}"
     - "--label=org.opencontainers.image.url=https://github.com/spacelift-io/spacectl"
     - "--label=org.opencontainers.image.documentation=https://github.com/spacelift-io/spacectl/blob/main/README.md"
     - "--label=org.opencontainers.image.source=https://github.com/spacelift-io/spacectl"
     - "--label=org.opencontainers.image.version={{ .Version }}"
     - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
     - "--label=org.opencontainers.image.created={{ time \"2006-01-02T15:04:05Z07:00\" }}"
    image_templates: ["ghcr.io/spacelift-io/spacectl:{{ .Version }}-amd64"]

  - use: buildx
    goarch: arm64
    build_flag_templates:
     - "--platform=linux/arm64"
     - "--label=org.opencontainers.image.title={{ .ProjectName }}"
     - "--label=org.opencontainers.image.vendor=Spacelift"
     - "--label=org.opencontainers.image.description=Spacelift CLI version {{ .Version }}"
     - "--label=org.opencontainers.image.url=https://github.com/spacelift-io/spacectl"
     - "--label=org.opencontainers.image.documentation=https://github.com/spacelift-io/spacectl/blob/main/README.md"
     - "--label=org.opencontainers.image.source=https://github.com/spacelift-io/spacectl"
     - "--label=org.opencontainers.image.version={{ .Version }}"
     - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
     - "--label=org.opencontainers.image.created={{ time \"2006-01-02T15:04:05Z07:00\" }}"
    image_templates: ["ghcr.io/spacelift-io/spacectl:{{ .Version }}-arm64"]

docker_manifests:
  - name_template: ghcr.io/spacelift-io/spacectl:{{ .Version }}
    image_templates:
    - ghcr.io/spacelift-io/spacectl:{{ .Version }}-amd64
    - ghcr.io/spacelift-io/spacectl:{{ .Version }}-arm64

  - name_template: ghcr.io/spacelift-io/spacectl:latest
    image_templates:
    - ghcr.io/spacelift-io/spacectl:{{ .Version }}-amd64
    - ghcr.io/spacelift-io/spacectl:{{ .Version }}-arm64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  draft: false
  extra_files:
    - glob: ./key.*

changelog:
  use: github-native

brews:
  - name: "{{ .ProjectName }}"
    tap:
      owner: "spacelift-io"
      name: "homebrew-spacelift"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/spacelift-io/spacectl
    description: "Spacelift client and CLI"
    license: "MIT"
